# Generated by Django 4.1.5 on 2023-02-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_alter_project_id_review_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='review_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='review_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='vote',
            field=models.CharField(blank=True, choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=20, null=True),
        ),
    ]
