# Generated by Django 4.1.5 on 2023-02-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_review_number_project_review_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, default='default.svg', null=True, upload_to=''),
        ),
    ]
